name: tests

on:
  push:
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        laravel: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
    name: Tests for Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require laravel/laravel:"${{ matrix.laravel }}" --dev --no-update
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test-laravel

  lumen:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        lumen: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*]
    name: Tests for Lumen ${{ matrix.lumen }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require laravel/lumen:"${{ matrix.lumen }}" --dev --no-update
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: composer test-lumen
